Identity
Skava600/RecordHub pull request #1
Opened 2023-06-14 12:05 UTC by Skava600

2023-07-13 15:32 UTC, Y45K0VL3V requested changes
So overall, it's an old PR and you might already fix many of these mistakes. Good for first time

Maybe imho but don't really like the idea of DI implementation (each project has own extensions):
  1. Uncomfortable to look for all this service registrations.
  2. The moment of registration service of one layer in the other one.
  
Also don't like, that Application layer (called Core in your case) doesn't contain services, but it could. Any mail service, remote api services(clients) etc - infrastructure. What about service, that aren't connect to smth remote or just not in application(product) bounds, they should be located in application layer.

Just my vision.

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Infrastructure/Configuration/JwtConfig.cs
> +        public string Key { get; set; } = "mysecretkey123";  // ключ для шифрации
Guess, it will be more comfortable to put configuration in appsettings. And maybe try to exlore options pattern, if you want to bind it to a c# model class.

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Infrastructure/Publishers/SendEmailPublisher.cs
> +
empty line

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Infrastructure/ServiceExtensions.cs
> +
empty line

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Core/Mappers/UserProfile.cs
> +
empty line

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Core/Services/IAccountService.cs
> +        Task SendEmailVerificationAsync(string? userId,
Use the style, that you use above: if you have a long method, class, etc declaration and you move them on a new line, then make sure to separate every parameter with a new line, even with method name.
Make it everywhere

2023-07-13 15:32 UTC, Y45K0VL3V commented on docker-compose.yml
> +
empty line

2023-07-13 15:32 UTC, Y45K0VL3V commented on docker-compose.yml
> +        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
tabs here and above

2023-07-13 15:32 UTC, Y45K0VL3V commented on docker-compose.yml
> +          - gateway
different tabs

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Core/Exceptions/AddingToRoleException.cs
> +        public AddingToRoleException(IEnumerable<IdentityError> errors) : base(errors, AddingToRoleExceptionMessage)
New line before constructor and ": base..." on new line.
Fix it everywhere.

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Domain/Models/LoginModel.cs
> +        [Required]
Why not to make all the other models validation with FluentValidation?

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Infrastructure/ServiceExtensions.cs
> +                        return Task.CompletedTask;
Always leave an empty line before return.

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Infrastructure/ServiceExtensions.cs
> +            return services;
the same with new line before return.
Fix it everywhere

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Infrastructure/Services/AccountService.cs
> +        public AccountService(
Empty line before constructor

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Infrastructure/Services/AccountService.cs
> +          )
Recommended to use one style. You can leave a bracket either on the line with last parameter, as you have already done in some cases, or separate it with new line, as here is. Choose one way. Personally I think, that better to let it stay on the line with last parameter.

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Infrastructure/Services/AccountService.cs
> +            result = await _userManager.AddToRoleAsync(user, nameof(Roles.User));
Use the other variable.

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Persistence/Data/Repositories/Implementation/BaseRepository.cs
> +        private readonly DbSet<T> _dbSet;
Usually private modifier used with fields and public with properties. Use readonly with context.

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Persistence/DbInitializer.cs
> +        private readonly AccountDbContext ctx;
private fields template: _camelCase

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Persistence/ServiceExtensions.cs
> +    opt.TokenLifespan = TimeSpan.FromHours(2));
tabs

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Persistence/ServiceExtensions.cs
> +                opt.TokenLifespan = TimeSpan.FromDays(3));
lifetimes can be moved to appsettings

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.Shared/Config/LoggingConfig.cs
> +                logLevel = LogEventLevel.Information;
Always write brackets to follow a single codestyle

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.Shared/Config/LoggingConfig.cs
> +                   needAutoCreateTable: true,
tab

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.Shared/Models/MailData.cs
> +        public List<string> To { get; }
Missed empty line

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.Shared/Models/MailData.cs
> +        public MailData(List<string> to, string subject, string? body = null, string? from = null, string? displayName = null, string? replyTo = null, string? replyToName = null, List<string>? bcc =
too long line

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.Shared/Services/Logging/AppLogging.cs
> +        {
check tabs this file

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Api/Controllers/AuthController.cs
> +        [HttpPut]
Put?

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Api/Controllers/AuthController.cs
> +        public async Task<IActionResult> VerifyEmailAsync(CancellationToken cancellationToken = default)
method name the same as above, but different responsibilities.

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Api/appsettings.json
> +
spaces

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Domain/Constants/Constants.cs
> +        public const int TokenLifeTime = 120;
appsettings?

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Infrastructure/ServiceExtensions.cs
> +        private static IServiceCollection InjectCoreServices(this IServiceCollection services)
Does Infrastructure really injecting core services???

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Infrastructure/ServiceExtensions.cs
> +                    cfg.Host("rabbitmq://messagebus", h =>
Can be located in appsettings

2023-07-13 15:32 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Infrastructure/Services/AddressService.cs
> +            await _validator.ValidateAndThrowAsync(model, cancellationToken);
As i saw, you provide AddressModel directly from controller to service with no changes. So to validate it earlier FluentValidation has DI extensions to add model validation at the moment of starting process it in the controller endpoint.

2023-07-14 07:28 UTC, Skava600 commented on RecordHub.IdentityService/RecordHub.IdentityService.Infrastructure/Configuration/JwtConfig.cs
> +        public string Key { get; set; } = "mysecretkey123";  // ключ для шифрации
i have config in users secrets, but you have a point, better to remove this initializing

2023-07-14 13:19 UTC, Skava600 commented on RecordHub.IdentityService/RecordHub.IdentityService.Api/Controllers/AuthController.cs
> +        [HttpPut]
this action could make column  emailconfirmed in db be true, if token is valid, so i thought it should be put

2023-07-14 13:31 UTC, Skava600 commented on RecordHub.IdentityService/RecordHub.IdentityService.Infrastructure/Services/AddressService.cs
> +            await _validator.ValidateAndThrowAsync(model, cancellationToken);
You mean to move validation to controller method? Or some automatic validation of models. If You mean the last one, then docs saying its not possible for not mvc apps

2023-07-14 13:42 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Api/Controllers/AuthController.cs
> +        [HttpPut]
Put usually used when you want to modify any model and provide fully complete fields (with all the modifies). In this case it's not directly aimed to edit smth. So here should be POST method.

Btw, use Patch method when editing just a single field (f.e. endpoint api/user/change-name/ , you need just to pass new name)

2023-07-14 14:19 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Infrastructure/Services/AddressService.cs
> +            await _validator.ValidateAndThrowAsync(model, cancellationToken);
Hm, try to use .AddFluentValidationAutoValidation();
Guess it worked in my case (also not mvc project). If it won't work properly, leave it like it is.

2023-07-17 16:44 UTC, Y45K0VL3V requested changes

2023-07-17 16:44 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Api/Program.cs
> +builder.Services.AddFluentValidationAutoValidation();
1 auto validation

2023-07-17 16:44 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Api/Program.cs
> +builder.Services.AddFluentValidationAutoValidation();
2 auto validation)

2023-07-17 16:44 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Core/Validators/RegisterModelValidator.cs
> +                .Matches("@\"^\\+375\\d{9}$")
fix)

2023-07-17 16:58 UTC, Y45K0VL3V approved these changes

2023-07-17 17:06 UTC, merged

2023-07-17 17:07 UTC, Y45K0VL3V approved these changes