Gateway: configure ocelot.json.
Skava600/RecordHub pull request #2
Opened 2023-06-15 11:00 UTC by Skava600

2023-07-13 15:56 UTC, Y45K0VL3V requested changes

2023-07-13 15:56 UTC, Y45K0VL3V commented on RecordHub.Gateway/Program.cs
> +app.UseRouting();
Double UseRouting. No two commands in one line.

2023-07-13 15:56 UTC, Y45K0VL3V commented on RecordHub.Gateway/ocelot.json
> +      // Identity service
Is this file should be removed? Does its place will be taken by ocelot.json files, that in Config/Ocelot?

2023-07-13 16:14 UTC, Skava600 commented on RecordHub.Gateway/ocelot.json
> +      // Identity service
I wanted to implement merging of ocelot files that located in config/ocelot, but its not supporting swagger for ocelot, so i just keeped these files for the case if i would remove swagger an implement client app

2023-07-13 16:28 UTC, Y45K0VL3V commented on RecordHub.Gateway/ocelot.json
> +      // Identity service
Got it

2023-07-17 16:26 UTC, Y45K0VL3V approved these changes

2023-07-17 17:21 UTC, merged