Mail service
Skava600/RecordHub pull request #3
Opened 2023-06-21 13:51 UTC by Skava600

2023-07-13 16:26 UTC, Y45K0VL3V requested changes

2023-07-13 16:26 UTC, Y45K0VL3V commented on RecordHub.MailService/RecordHub.MailService.Api/Buffer-20230623.txt
> +{"@timestamp":"2023-06-23T07:47:33.6221700+00:00","message":"Connection Failed: rabbitmq://messagebus/","level":"warning","exception":{"ClassName":"RabbitMQ.Client.Exceptions.BrokerUnreachableExcepti
You should better configure gitignore)

2023-07-13 16:26 UTC, Y45K0VL3V commented on RecordHub.MailService/RecordHub.MailService.Api/Middleware/GlobalExceptionHandlerMiddleware.cs
> +    {
TODO?)

2023-07-13 16:26 UTC, Y45K0VL3V commented on RecordHub.MailService/RecordHub.MailService.Api/Program.cs
> +
many empty lines

2023-07-13 16:26 UTC, Y45K0VL3V commented on RecordHub.MailService/RecordHub.MailService.Api/Program.cs
> +var app = builder.Build();
Maybe just a new line before Build()?

2023-07-13 16:26 UTC, Y45K0VL3V commented on RecordHub.MailService/RecordHub.MailService.Infrastructure/Config/LoggingConfig.cs
> +
remove line

2023-07-13 16:26 UTC, Y45K0VL3V commented on RecordHub.MailService/RecordHub.MailService.Infrastructure/Config/LoggingConfig.cs
> +                logLevel = LogEventLevel.Information;
brackets

2023-07-13 16:26 UTC, Y45K0VL3V commented on RecordHub.MailService/RecordHub.MailService.Infrastructure/Config/LoggingConfig.cs
> +            var log = new LoggerConfiguration()
line after if/else/while etc.

2023-07-13 16:26 UTC, Y45K0VL3V commented on RecordHub.MailService/RecordHub.MailService.Infrastructure/Consumers/SendEmailConsumer.cs
> +        private readonly IMailService mailService;
Wrong private field name convention

2023-07-13 16:26 UTC, Y45K0VL3V commented on RecordHub.MailService/RecordHub.MailService.Infrastructure/ServiceExtensions.cs
> +                        h.Username("guest");
appsettings

2023-07-13 16:26 UTC, Y45K0VL3V commented on RecordHub.MailService/RecordHub.MailService.Infrastructure/Services/MailService.cs
> +                mail.To.Add(MailboxAddress.Parse(mailAddress));
also brackets

2023-07-13 16:26 UTC, Y45K0VL3V commented on RecordHub.MailService/RecordHub.MailService.Infrastructure/Services/MailService.cs
> +            return true;
Does false possible?

2023-07-14 13:34 UTC, Skava600 commented on RecordHub.MailService/RecordHub.MailService.Api/Middleware/GlobalExceptionHandlerMiddleware.cs
> +    {
Hah yeah, I forgot)

2023-07-17 16:24 UTC, Y45K0VL3V approved these changes

2023-07-17 17:09 UTC, merged