Identity tests #861n34x88
Skava600/RecordHub pull request #8
Opened 2023-07-20 08:58 UTC by Skava600

2023-07-21 07:22 UTC, Y45K0VL3V requested changes
So, just fix everywhere what i mark in first file (mocks setup, test data, fluent assertions)

2023-07-21 07:22 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Tests/AccountControllerTests.cs
> +            accountServiceMock
All setups put in another file, then you call them one time in constructor

2023-07-21 07:22 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Tests/AccountControllerTests.cs
> +            var okResult = Assert.IsType<OkObjectResult>(result);
Just use fluent assertions everywhere

2023-07-21 07:22 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Tests/AccountControllerTests.cs
> +            var expectedUser = new UserDTO
this data should be located in another file

2023-07-21 12:51 UTC, Skava600 commented on RecordHub.IdentityService/RecordHub.IdentityService.Tests/AccountControllerTests.cs
> +            var okResult = Assert.IsType<OkObjectResult>(result);
Should i keep moq assertion? f.e:
   _mockUserManager
       .Verify(m => m
       .AddToRoleAsync(
           It.IsAny<User>(),
           It.IsAny<string>()),
       Times.Once);

2023-07-21 15:41 UTC, Y45K0VL3V commented on RecordHub.IdentityService/RecordHub.IdentityService.Tests/AccountControllerTests.cs
> +            var okResult = Assert.IsType<OkObjectResult>(result);
yes

2023-07-24 09:34 UTC, Y45K0VL3V approved these changes

2023-07-24 10:00 UTC, merged