Catalog tests
Skava600/RecordHub pull request #9
Opened 2023-07-26 14:56 UTC by Skava600

2023-07-26 17:11 UTC, Y45K0VL3V requested changes

2023-07-26 17:11 UTC, Y45K0VL3V commented on RecordHub.CatalogService/RecordHub.CatalogService.Api/Program.cs
> +public partial class Program { }
Do you need it?

2023-07-26 17:11 UTC, Y45K0VL3V commented on RecordHub.CatalogService/RecordHub.CatalogService.Tests/Generators/BaseEntityGenerator.cs
> +
remove empty line

2023-07-26 17:11 UTC, Y45K0VL3V commented on RecordHub.CatalogService/RecordHub.CatalogService.Tests/IntegrationTests/Helpers/CustomWebApplicationFactory.cs
> +     : WebApplicationFactory<TProgram>, IAsyncLifetime where TProgram : class
Missed the tab (or it's just github's trouble)

2023-07-26 17:11 UTC, Y45K0VL3V commented on RecordHub.CatalogService/RecordHub.CatalogService.Tests/IntegrationTests/StylesControllerTests.cs
> +        public async Task CreateAsync_ReturnsOkResponse()
Test naming always the same "MethodName_StateUnderTest_ExpectedBehavior"

2023-07-26 17:11 UTC, Y45K0VL3V commented on RecordHub.CatalogService/RecordHub.CatalogService.Tests/UnitTests/Services/StyleCatalogServiceTests.cs
> +                    new Record { Id = Guid.NewGuid(), Name = "Record 1",  },
extra space at the end

2023-07-26 17:14 UTC, Skava600 commented on RecordHub.CatalogService/RecordHub.CatalogService.Api/Program.cs
> +public partial class Program { }
Yes - for CustomWebApplicationFactory, without it is not seeing Program class

2023-07-27 15:44 UTC, Y45K0VL3V approved these changes

2023-07-27 19:02 UTC, merged